import type { Faq, PricingPackage, Service } from "@/lib/cms";

/**
 * Starter content used as a read fallback when a Firestore collection is still
 * empty, and as the payload for the "Load starter content" action in /admin.
 * Service document IDs are their slug, so packages reference them by slug.
 */
export const DEFAULT_SERVICES: Service[] = [
  {
    id: "custom-website",
    name: "Custom Website",
    slug: "custom-website",
    description:
      "Hand-built responsive websites with custom design, animations and complete source files.",
    category: "websites",
    icon: "Globe",
    starting_price: "₹120",
    features: ["Custom design", "Fully responsive", "Smooth animations", "Complete project ZIP"],
    active: true,
    display_order: 1,
  },
  {
    id: "custom-discord-bot",
    name: "Custom Discord Bot",
    slug: "custom-discord-bot",
    description: "Discord bots built to your spec: moderation, tickets, automation and databases.",
    category: "discord_bots",
    icon: "Bot",
    starting_price: "₹299",
    features: ["Custom commands", "Moderation & logging", "Ticket systems", "Full source code"],
    active: true,
    display_order: 2,
  },
  {
    id: "custom-discord-server",
    name: "Custom Discord Server",
    slug: "custom-discord-server",
    description:
      "Professionally structured Discord servers with roles, permissions and full branding.",
    category: "discord_servers",
    icon: "Users",
    starting_price: "₹99",
    features: [
      "Categories & channels",
      "Roles & permissions",
      "Verification & tickets",
      "Server branding",
    ],
    active: true,
    display_order: 3,
  },
  {
    id: "domain-hosting",
    name: "Domain & Hosting Setup",
    slug: "domain-hosting",
    description:
      "Deployment help and hosting guidance. Deployment is free when you bring your own domain/hosting.",
    category: "hosting",
    icon: "Server",
    starting_price: "FREE",
    features: [
      "Free deployment",
      "Free project ZIP",
      "Free hosting options where suitable",
      "Domain guidance",
    ],
    active: true,
    display_order: 4,
  },
  {
    id: "extras",
    name: "Extra Services",
    slug: "extras",
    description:
      "Add-ons for existing projects: extra pages, features, revisions and urgent delivery.",
    category: "extras",
    icon: "Plus",
    starting_price: "₹30",
    features: ["Extra pages", "Extra features", "Extra revisions", "Urgent delivery"],
    active: true,
    display_order: 5,
  },
];

type PackageSeed = Omit<PricingPackage, "id"> & { id: string };

function pkg(
  id: string,
  service_id: string,
  name: string,
  price: number,
  price_suffix: string,
  description: string,
  features: string[],
  popular: boolean,
  display_order: number,
): PackageSeed {
  return {
    id,
    service_id,
    name,
    price,
    price_suffix,
    description,
    features,
    popular,
    active: true,
    display_order,
  };
}

export const DEFAULT_PACKAGES: PricingPackage[] = [
  pkg(
    "web-basic",
    "custom-website",
    "Basic",
    120,
    "",
    "Perfect single-page presence.",
    [
      "1 page",
      "Custom design",
      "Mobile + PC responsive",
      "Custom text/images",
      "Basic animations",
      "Minor changes",
      "Complete ZIP project",
    ],
    false,
    1,
  ),
  pkg(
    "web-standard",
    "custom-website",
    "Standard",
    250,
    "",
    "Small multi-page site.",
    [
      "Up to 3 pages",
      "Custom UI",
      "Responsive design",
      "Animations",
      "Custom sections",
      "Minor revisions",
      "Complete ZIP project",
    ],
    true,
    2,
  ),
  pkg(
    "web-premium",
    "custom-website",
    "Premium",
    400,
    "",
    "Premium UI with interactions.",
    [
      "Up to 5 pages",
      "Premium custom UI",
      "Advanced animations",
      "Interactive elements",
      "Custom layout",
      "Revisions",
      "Complete ZIP project",
    ],
    false,
    3,
  ),
  pkg(
    "web-advanced",
    "custom-website",
    "Advanced",
    600,
    "+",
    "Complex, feature-rich builds.",
    [
      "5+ pages",
      "Advanced UI/UX",
      "Complex features",
      "API/integration where applicable",
      "Advanced animations",
      "Complete project ZIP",
      "Final price based on requirements",
    ],
    false,
    4,
  ),
  pkg(
    "bot-basic",
    "custom-discord-bot",
    "Basic",
    299,
    "",
    "Essential bot systems.",
    [
      "Basic custom commands",
      "Welcome system",
      "Auto-role",
      "Basic moderation",
      "Custom embeds",
      "Source files",
    ],
    false,
    1,
  ),
  pkg(
    "bot-standard",
    "custom-discord-bot",
    "Standard",
    499,
    "",
    "Everything in Basic plus more.",
    [
      "Ticket system",
      "Advanced moderation",
      "Logging",
      "Custom commands",
      "Configuration",
      "Source files",
    ],
    true,
    2,
  ),
  pkg(
    "bot-advanced",
    "custom-discord-bot",
    "Advanced",
    799,
    "",
    "Everything in Standard plus database.",
    [
      "Database features",
      "Advanced ticket system",
      "Custom automation",
      "Multiple custom systems",
      "Source code",
      "Setup instructions",
    ],
    false,
    3,
  ),
  pkg(
    "bot-premium",
    "custom-discord-bot",
    "Premium",
    1199,
    "+",
    "Large-scale custom bot.",
    [
      "Large custom bot",
      "Multiple advanced systems",
      "Database",
      "Custom automation",
      "Advanced commands",
      "Complete source code",
      "Setup documentation",
    ],
    false,
    4,
  ),
  pkg(
    "server-basic",
    "custom-discord-server",
    "Basic",
    99,
    "",
    "Clean starter structure.",
    ["Categories", "Channels", "Basic roles", "Permissions", "Basic server structure"],
    false,
    1,
  ),
  pkg(
    "server-standard",
    "custom-discord-server",
    "Standard",
    199,
    "",
    "Organised community setup.",
    [
      "Custom categories/channels",
      "Custom roles",
      "Permissions",
      "Welcome setup",
      "Basic bot setup",
      "Server organization",
    ],
    false,
    2,
  ),
  pkg(
    "server-premium",
    "custom-discord-server",
    "Premium",
    399,
    "",
    "Complete managed structure.",
    [
      "Complete server structure",
      "Advanced roles & permissions",
      "Ticket system",
      "Verification",
      "Moderation setup",
      "Welcome system",
      "Custom embeds",
    ],
    true,
    3,
  ),
  pkg(
    "server-advanced",
    "custom-discord-server",
    "Advanced",
    699,
    "+",
    "Large community server.",
    [
      "Large community server",
      "Complete role hierarchy",
      "Advanced permissions",
      "Multiple bot systems",
      "Ticket + verification",
      "Moderation",
      "Custom server branding",
    ],
    false,
    4,
  ),
  pkg(
    "extra-page",
    "extras",
    "Extra Website Page",
    50,
    "+",
    "Add another page to your site.",
    ["Matching design", "Responsive", "Included animations"],
    false,
    1,
  ),
  pkg(
    "extra-feature",
    "extras",
    "Extra Major Website Feature",
    50,
    "+",
    "A significant new website feature.",
    ["Custom functionality", "Tested & integrated"],
    false,
    2,
  ),
  pkg(
    "extra-revision",
    "extras",
    "Extra Revision",
    30,
    "+",
    "Additional round of changes.",
    ["Content or design tweaks"],
    false,
    3,
  ),
  pkg(
    "extra-deployment",
    "extras",
    "Website Deployment",
    0,
    "",
    "Free when you bring domain & hosting.",
    ["Deployment setup", "Free of charge"],
    false,
    4,
  ),
  pkg(
    "extra-bot-feature",
    "extras",
    "Custom Discord Bot Feature",
    50,
    "+",
    "Extra bot command or system.",
    ["New command/system", "Source included"],
    false,
    5,
  ),
  pkg(
    "extra-urgent",
    "extras",
    "Urgent Delivery",
    50,
    "+",
    "Priority turnaround.",
    ["Faster delivery", "Priority support"],
    false,
    6,
  ),
];

export const DEFAULT_FAQS: Faq[] = [
  {
    id: "faq-timeline",
    question: "How long does a project take?",
    answer:
      "Most websites take 1-3 days, Discord bots 2-5 days and Discord servers under 2 days depending on complexity.",
    category: "general",
    active: true,
    display_order: 1,
  },
  {
    id: "faq-source",
    question: "Do I get the source code?",
    answer:
      "Yes. Every website comes as a complete project ZIP and every bot includes full source code with setup instructions.",
    category: "general",
    active: true,
    display_order: 2,
  },
  {
    id: "faq-hosting",
    question: "Is domain and hosting included in the price?",
    answer:
      "No. Domain and hosting are not included in service prices. If you provide your own, deployment is completely FREE.",
    category: "hosting",
    active: true,
    display_order: 3,
  },
  {
    id: "faq-changes",
    question: "What if I need changes after delivery?",
    answer: "Minor changes are included. Additional revisions are available from ₹30+ each.",
    category: "general",
    active: true,
    display_order: 4,
  },
  {
    id: "faq-payments",
    question: "How do payments work?",
    answer:
      "Payments are arranged directly after we agree on the scope. Just request a quote and we will confirm the final price.",
    category: "payments",
    active: true,
    display_order: 5,
  },
  {
    id: "faq-later",
    question: "Can you add features later?",
    answer:
      "Absolutely. Extra pages, bot features and server systems can be added any time from ₹50+.",
    category: "general",
    active: true,
    display_order: 6,
  },
];

export const DEFAULT_SETTINGS: Record<string, Record<string, unknown>> = {
  hero: {
    title: "Build. Launch. Grow.",
    subtitle:
      "Custom websites, Discord bots and professional Discord servers built according to your requirements.",
    eyebrow: "Digital development studio",
    primary_cta: "View Services",
    secondary_cta: "View Portfolio",
    tertiary_cta: "Get Started",
  },
  about: {
    title: "A small studio with a sharp focus",
    description:
      "We build custom websites, Discord bots and Discord servers for creators, communities and small businesses. Every project is built from scratch to your requirements — no templates, no bloat, and you always get the complete source files.",
  },
  why_us: {
    heading: "Why choose us",
    description: "Straightforward pricing, fast delivery and code you actually own.",
    features: [
      {
        title: "Built to your spec",
        description: "Every project is designed around your requirements, not a template.",
      },
      { title: "Fast delivery", description: "Most projects are delivered within a few days." },
      {
        title: "You own the code",
        description: "Complete project ZIP or bot source code with every order.",
      },
      {
        title: "Free deployment",
        description: "Bring your own domain and hosting and deployment costs nothing.",
      },
      { title: "Transparent pricing", description: "Clear package pricing with no hidden fees." },
      { title: "Ongoing support", description: "Add features or revisions whenever you need them." },
    ],
  },
  footer: {
    business_name: "NexusCrafters",
    logo_url: "/nexus-crafters-logo.png",
    description:
      "Custom websites, Discord bots and professional Discord servers for creators and small businesses.",
    email: "hello@novacraft.studio",
    discord: "",
    phone: "",
    socials: [
      { label: "Discord", url: "#" },
      { label: "GitHub", url: "#" },
      { label: "X", url: "#" },
    ],
  },
  hosting: {
    title: "Domain & Hosting",
    description:
      "Domain and hosting are not included in service prices. If you provide your own domain and hosting, deployment is FREE. If you do not have them, you still receive the complete project ZIP for free and can host it anywhere.",
  },
};
